### PR TITLE
Process termination when main process fails

### PR DESCRIPTION
**Pull request by tomascasas**
It seems that deep in promises the `try/catch` block in `main` will not terminate the main process.
As a result the container cannot collect the zombie pod to attempt restarting it.
This happens, though not limited to, when `Redis` is unavailable at boot time.

### CODE REVIEW

**Review by cjus — COMMENTED** [review]
Is the use of pyton3 necessary here?  Also what's the -U flag on the apk command?  Looks like this PR could be cleaner and more focused.

**Comment by tomascasas** [comment]
> Is the use of pyton3 necessary here? Also what's the -U flag on the apk command? Looks like this PR could be cleaner and more focused.

`python` was already there. That called my attention but if it is not used I can certainly kill it.
The reason for `python3` is because `python` package is RIP. And the image would not build unless by picking `python2` or `python3`. Tyler recommended the latter. if needed. Which I think based on you comment, it is not.

That `-U` is the syntax I've been using on other images in Skafos like the following, to get latest updates and bug fixes, it is a single liner for [apk update && apk upgrade](https://wiki.alpinelinux.org/wiki/Package_management#Upgrade_a_Running_System).
```
RUN apk -U upgrade \
  && apk add --no-cache \
    git
```
The [`--no-cache` option](https://stackoverflow.com/a/49119046) takes care of these two `--update` and `  && rm -rf /var/cache/apk/*` from this block:
```
RUN apk add --update \
    curl \
    python \
    build-base \
  && rm -rf /var/cache/apk/*
```

Will remove `python*.  build and make sure it remains operational.

**Comment by tomascasas** [comment]
@cjus I removed `python*` from the list of packages to add to `alpine-12` and the service remained operational.
As mentioned before, the syntax used to get latest package updates and install them without caching, thus removing the need for the cleanup stmt is shorter and uses an already implemented feature towards cleanup.

**Comment by cjus** [comment]
Thanks @tomascasas looks good.

**Comment by tomascasas** [comment]
@cjus pls, let me know if you are able to build the new image and push it to docker hub. Thank you very much!

**Pull request merged**
